//! Registers every `illustrations/*.mdpc` as a built-in point cloud, so a
//! new built-in is exactly one file dropped into that folder.

use std::path::Path;

/// The engine features. With all of them on, the build sets the `all_engines`
/// cfg: shared engine API that only some engines read is checked for dead
/// code there, and not in builds that leave engines out.
const ENGINES: &[&str] = &[
    "PARTICLES",
    "LED",
    "SPLITFLAP",
    "BLOCKS",
    "LINE",
    "SKETCH",
    "WATERCOLOUR",
    "DARKROOM",
    "THERMAL",
];

fn main() {
    println!("cargo::rustc-check-cfg=cfg(all_engines)");
    if ENGINES
        .iter()
        .all(|e| std::env::var_os(format!("CARGO_FEATURE_{e}")).is_some())
    {
        println!("cargo::rustc-cfg=all_engines");
    }

    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dir = Path::new(&manifest).join("illustrations");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "mdpc"))
        .map(|p| {
            let stem = p
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or_default()
                .to_string();
            let ok = !stem.is_empty()
                && stem
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-');
            assert!(
                ok,
                "illustration file `{}` needs a name of lowercase letters, digits and hyphens",
                p.display()
            );
            stem
        })
        .collect();
    names.sort();
    // The built-in illustrations belong to the particles engine: a build
    // without the `particles` feature ships none.
    if std::env::var_os("CARGO_FEATURE_PARTICLES").is_none() {
        names.clear();
    }

    let mut out = String::from(
        "/// Built-in clouds: (name, document), generated by build.rs from\n/// `crates/mdeck/illustrations/*.mdpc`, sorted by name.\nconst BUILTIN: &[(&str, &str)] = &[\n",
    );
    for n in &names {
        let path = dir.join(format!("{n}.mdpc"));
        println!("cargo:rerun-if-changed={}", path.display());
        out.push_str(&format!(
            "    ({n:?}, include_str!({:?})),\n",
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    std::fs::write(Path::new(&out_dir).join("builtin_illustrations.rs"), out)
        .expect("writing the built-in illustration registry");
}
